domain:
  name: "logistics"
  requirements:
    equality: False
    strips: True
    typing: True
  types:
    - { type_names: ["truck, airplane"], parent_type: "vehicle" }
    - { type_names: ["package, vehicle"], parent_type: "physobj" }
    - { type_names: ["airport, location"], parent_type: "place" }
    - { type_names: ["city, place, physobj"], parent_type: "object" }
  predicates:
    - name: "in-city"
      params:
        - { name: "loc", type: "place" }
        - { name: "city", type: "city" }
    - name: "at"
      params:
        - { name: "obj", type: "physobj" }
        - { name: "loc", type: "place" }
    - name: "in"
      params:
        - { name: "pkg", type: "package" }
        - { name: "veh", type: "vehicle" }
  actions:
    - name: "LOAD-TRUCK"
      params:
        - { name: "pkg", type: "package" }
        - { name: "truck", type: "truck" }
        - { name: "loc", type: "place" }
      preconditions:
        - { name: "at", args: ["truck", "loc"] }
        - { name: "at", args: ["pkg", "loc"] }
      effects:
        - { name: "at", args: ["pkg", "loc"], not: true }
        - { name: "in", args: ["pkg", "truck"] }
    - name: "LOAD-AIRPLANE"
      params:
        - { name: "pkg", type: "package" }
        - { name: "airplane", type: "airplane" }
        - { name: "loc", type: "place" }
      preconditions:
        - { name: "at", args: ["pkg", "loc"] }
        - { name: "at", args: ["airplane", "loc"] }
      effects:
        - { name: "at", args: ["pkg", "loc"], not: true }
        - { name: "in", args: ["pkg", "airplane"] }
    - name: "UNLOAD-TRUCK"
      params:
        - { name: "pkg", type: "package" }
        - { name: "truck", type: "truck" }
        - { name: "loc", type: "place" }
      preconditions:
        - { name: "at", args: ["truck", "loc"] }
        - { name: "in", args: ["pkg", "truck"] }
      effects:
        - { name: "in", args: ["pkg", truck""], not: true }
        - { name: "at", args: ["pkg", "loc"] }
    - name: "UNLOAD-AIRPLANE"
      params:
        - { name: "pkg", type: "package" }
        - { name: "airplane", type: "airplane" }
        - { name: "loc", type: "place" }
      preconditions:
        - { name: "in", args: ["pkg", "airplane"] }
        - { name: "at", args: ["airplane", "loc"] }
      effects:
        - { name: "in", args: ["pkg", "airplane"], not: true }
        - { name: "at", args: ["pkg", "loc"] }
    - name: "DRIVE-TRUCK"
      params:
        - { name: "truck", type: "truck" }
        - { name: "loc-from", type: "place" }
        - { name: "loc-to", type: "place" }
        - { name: "city", type: "city" }
      preconditions:
        - { name: "truck", args: ["loc-from"] }
        - { name: "in-city", args: ["loc-from", "city"] }
        - { name: "in-city", args: ["loc-to", "city"] }
      effects:
        - { name: "at", args: ["truck", "loc-fro"], not: true }
        - { name: "at", args: ["truck", "loc-to"] }
   - name: "FLY-AIRPLANE"
     params:
       - { name: "airplane", type: "airplane" }
       - { name: "loc-from", type: "airport" }
       - { name: "loc-to", type: "airport" }
     preconditions:
       - { name: "at", args: ["airplane", "loc-from"] }
     effects:
       - { name: "at", args: ["airplane", "loc-from"], not: true }
       - { name: "at", args: ["airplane", "loc-to"] }
