domain:
  name: "Depot"
  requirements:
    equality: False
    strips: False
    typing: True
  types:
    - { type_names: ["place, locatable"], parent_type: "object" }
    - { type_names: ["depot, distributor"], parent_type: "place" }
    - { type_names: ["truck, hoist, surface"], parent_type: "locatable" }
    - { type_names: ["pallet, crate"], parent_type: "surface" }
  predicates:
    - name: "at"
      params:
        - { name: "x", type: "locatable" }
        - { name: "y", type: "place" }
    - name: "on"
      params:
        - { name: "x", type: "crate" }
        - { name: "y", type: "surface" }
    - name: "in"
      params:
        - { name: "x", type: "crate" }
        - { name: "y", type: "truck" }
    - name: "lifting"
      params:
        - { name: "x", type: "hoist" }
        - { name: "y", type: "crate" }
    - name: "available"
      params:
        - { name: "x", type: "hoist" }
    - name: "clear"
      params:
        - { name: "x", type: "surface" }
  actions:
    - name: "Drive"
      params:
        - { name: "x", type: "truck" }
        - { name: "y", type: "place" }
        - { name: "z", type: "place" }
      preconditions:
        - { name: "at", args: ["x", "y"] }
      effects:
        - { name: "at", args: ["x", "y"], not: true }
        - { name: "at", args: ["x", "z"] }
    - name: "Lift"
      params:
        - { name: "x", type: "hoist" }
        - { name: "y", type: "crate" }
        - { name: "z", type: "surface" }
        - { name: "p", type: "place" }
      preconditions:
        - { name: "at", args: ["x", "p"] }
        - { name: "available", args: ["x"] }
        - { name: "at", args: ["y", "p"] }
        - { name: "on", args: ["y", "z"] }
        - { name: "clear", args: ["y"] }
      effects:
        - { name: "at", args: ["y", "p"], not: true }
        - { name: "lifting", args: ["x", "y"] }
        - { name: "clear", args: ["y"], not: true }
        - { name: "available", args: ["x"], not: true }
        - { name: "clear", args: ["z"] }
        - { name: "on", args: ["y", "z"], not: true }
    - name: "Drop"
      params:
        - { name: "x", type: "hoist" }
        - { name: "y", type: "crate" }
        - { name: "z", type: "surface" }
        - { name: "p", type: "place" }
      preconditions:
        - { name: "at", args: ["x", "p"] }
        - { name: "at", args: ["z", "p"] }
        - { name: "clear", args: ["z"] }
        - { name: "lifting", args: ["x", "y"] }
      effects:
        - { name: "available", args: ["x"] }
        - { name: "lifting", args: ["x", "y"], not: true }
        - { name: "at", args: ["y", "p"] }
        - { name: "clear", args: ["z"], not: true }
        - { name: "clear", args: ["y"] }
        - { name: "on", args: ["y", "z"] }
    - name: "Load"
      params:
        - { name: "x", type: "hoist" }
        - { name: "y", type: "crate" }
        - { name: "z", type: "truck" }
        - { name: "p", type: "place" }
      preconditions:
        - { name: "at", args: ["x", "p"] }
        - { name: "at", args: ["z", "p"] }
        - { name: "lifting", args: ["x", "y"] }
      effects:
        - { name: "lifting", args: ["x", "y"], not: true }
        - { name: "in", args: ["y", "z"] }
        - { name: "available", args: ["x"] }
    - name: "Unload"
      params:
        - { name: "x", type: "hoist" }
        - { name: "y", type: "crate" }
        - { name: "z", type: "truck" }
        - { name: "p", type: "place" }
      preconditions:
        - { name: "at", args: ["x", "p"] }
        - { name: "at", args: ["z", "p"] }
        - { name: "available", args: ["x"] }
        - { name: "in", args: ["y", "z"] }
      effects:
        - { name: "in", args: ["y", "z"], not: true }
        - { name: "available", args: ["x"], not: true }
        - { name: "lifting", args: ["x", "y"] }
