device:
  name: "device_0"
  type: "Robot"
  subtype: "AutonomousRobot"
  unique_properties:
    - { "model", "ur5" }
    - { "manufacturer", "universal_robot" }
  extra_properties:
    - { "description", "URDF description and properties of a Universal Robot UR5 robot arm" }
    - { "urdf_link", "https://raw.githubusercontent.com/ros-industrial/universal_robot/kinetic-devel/ur_description/urdf/ur5_robot.urdf.xacro" }
  capabilities:
    - name: "moving"
      properties:
        - { "degrees_of_freedom", 6 }
        - { "payload", 5 }
