single_robotic_system:
  name: "single_robotic_system_0"
  devices:
    - name: "device_0"
      class: "Robot" # ontogy has UpperCase
      subclass: "Subclass" # ontogy has UpperCase
      unique_properties:
        - { name: "bool_prop_", value: false }
        - { name: "int_prop_", value: 1 }
        - { name: "double_prop_", value: 0.1 }
        - { name: "string_prop_", value: "string" }
      extra_properties:
        - { name: "bool_prop_", value: false }
        - { name: "int_prop_", value: 1 }
        - { name: "double_prop_", value: 0.1 }
        - { name: "string_prop_", value: "string" }
      capabilities:
        - name: "capability"
          properties:
            - { name: "bool_prop_", value: false }
            - { name: "int_prop_", value: 1 }
            - { name: "double_prop_", value: 0.1 }
            - { name: "string_prop_", value: "string" }
    - name: "device_1"
      class: "Gripper" # ontogy has UpperCase
      subclass: "Subclass" # ontogy has UpperCase
      unique_properties:
        - { name: "bool_prop_", value: false }
        - { name: "int_prop_", value: 1 }
        - { name: "double_prop_", value: 0.1 }
        - { name: "string_prop_", value: "string" }
      extra_properties:
        - { name: "bool_prop_", value: false }
        - { name: "int_prop_", value: 1 }
        - { name: "double_prop_", value: 0.1 }
        - { name: "string_prop_", value: "string" }
      capabilities:
        - name: "capability"
          properties:
            - { name: "bool_prop_", value: false }
            - { name: "int_prop_", value: 1 }
            - { name: "double_prop_", value: 0.1 }
            - { name: "string_prop_", value: "string" }
  extra_properties:
    - { name: "bool_prop_", value: false }
    - { name: "int_prop_", value: 1 }
    - { name: "double_prop_", value: 0.1 }
    - { name: "string_prop_", value: "string" }
