problem:
  name: "gripper-x-1"
  domain: "gripper-typed"
  requirements:
    equality: False
    strips: False
    typing: True
  objects:
     - { name: "rooma", type: "room" }
     - { name: "roomb", type: "room" }
     - { name: "ball4", type: "ball" }
     - { name: "ball3", type: "ball" }
     - { name: "ball2", type: "ball" }
     - { name: "ball1", type: "ball" }
  init:
    - { name: "at-robby", args: ["rooma"] }
    - { name: "free", args: ["left"] }
    - { name: "free", args: ["right"] }
    - { name: "at", args: ["ball4", "rooma"] }
    - { name: "at", args: ["ball3", "rooma"] }
    - { name: "at", args: ["ball2", "rooma"] }
    - { name: "at", args: ["ball1", "rooma"] }
  goal:
    - { name: "at", args: ["ball4", "roomb"] }
    - { name: "at", args: ["ball3", "roomb"] }
    - { name: "at", args: ["ball2", "roomb"] }
    - { name: "at", args: ["ball1", "roomb"] }
