domain:
  name: "blocks"
  requirements:
    equality: False
    strips: False
    typing: True
  types:
    - {type_names: ["block"]}
  predicates:
    - name: "on"
      params:
        - { name: "x", type: "block" }
        - { name: "y", type: "block" }
    - name: "ontable"
      params:
        - { name: "x", type: "block" }
    - name: "clear"
      params:
        - { name: "x", type: "block" }
    - name: "handempty"
    - name: "holding"
      params:
        - { name: "x", type: "block" }
  actions:
    - name: "pick-up"
      params:
        - { name: "x", type: "block" }
      preconditions:
        - { name: "clear", zargs: ["x"] }
        - { name: "ontable", args: ["x"] }
        - { name: "handempty" }
      effects:
        - { name: "ontable", args: ["x"], not: true }
        - { name: "clear", args: ["x"], not: true }
        - { name: "handempty", not: true }
        - { name: "holding", args: ["x"] }
    - name: "put-down"
      params:
        - { name: "x", type: "block" }
      preconditions:
        - { name: "holding", args: ["x"] }
      effects:
        - { name: "holding", args: ["x"], not: true }
        - { name: "clear", args: ["x"] }
        - { name: "handempty" }
        - { name: "ontable", args: ["x"] }
    - name: "stack"
      params:
        - { name: "x", type: "block" }
        - { name: "y", type: "block" }
      preconditions:
        - { name: "holding", args: ["x"] }
        - { name: "clear", args: ["y"] }
      effects:
        - { name: "holding", args: ["x"], not: true }
        - { name: "clear", args: ["y"], not: true }
        - { name: "clear", args: ["x"] }
        - { name: "handempty" }
        - { name: "on", args: ["x", "y"] }
    - name: "unstack"
      params:
        - { name: "x", type: "block" }
        - { name: "y", type: "block" }
      preconditions:
        - { name: "on", args: ["x", "y"] }
        - { name: "clear", args: ["x"] }
        - { name: "handempty" }
      effects:
        - { name: "holding", args: ["x"] }
        - { name: "clear", args: ["y"] }
        - { name: "clear", args: ["x"], not: true }
        - { name: "handempty", not: true }
        - { name: "on", args: ["x", "y"], not: true }
