domain:
  name: "blocks"
  requirements:
    equality: False
    strips: False
    typing: True
  predicates:
    - cmd: "on"
      params:
      [
         {name: "x", type: "block"}, 
         {name: "y", type: "block"}
      ]
    - cmd: "ontable"
      params:
      [
         {name: "x", type: "block"}
      ]
    - cmd: "clear"
      params:
      [
         {name: "x", type: "block"}
      ]
    - cmd: "handempty"
    - cmd: "holding"
      params:
      [
         {name: "x", type: "block"}
      ]    
  actions:
    - name: "pick-up"
      params: 
      [
         {name: "x", type: "block"}
      ]
      preconditions:
      [
         {cmd: "clear", args: ["x"]},
         {cmd: "ontable", args: ["x"]},
         {cmd: "handempty"}
      ] 
      effects:
      [
         {cmd: "ontable", args: ["x"], not: true},
         {cmd: "clear", args: ["x"], not: true},
         {cmd: "handempty", not: true},
         {cmd: "holding", args: ["x"]}
      ] 
    - name: "put-down"
      params: 
      [
         {name: "x", type: "block"}
      ]
      preconditions:
      [
         {cmd: "holding", args: ["x"]}
      ] 
      effects:
      [
         {cmd: "holding", args: ["x"], not: true},
         {cmd: "clear", args: ["x"]},
         {cmd: "handempty"},
         {cmd: "ontable", args: ["x"]}
      ] 
    - name: "stack"
      params: 
      [
         {name: "x", type: "block"}, 
         {name: "y", type: "block"}
      ]
      preconditions:
      [
         {cmd: "holding", args: ["x"]},
         {cmd: "clear", args: ["y"]}
      ] 
      effects:
      [
         {cmd: "holding", args: ["x"], not: true},
         {cmd: "clear", args: ["y"], not: true},
         {cmd: "clear", args: ["x"]},
         {cmd: "handempty"},
         {cmd: "on", args: ["x", "y"]}
      ] 
    - name: "unstack"
      params: 
      [
         {name: "x", type: "block"}, 
         {name: "y", type: "block"}
      ]
      preconditions:
      [
         {cmd: "on", args: ["x", "y"]},
         {cmd: "clear", args: ["x"]},
         {cmd: "handempty"}
      ] 
      effects:
      [
         {cmd: "holding", args: ["x"]},
         {cmd: "clear", args: ["y"]},
         {cmd: "clear", args: ["x"], not: true},
         {cmd: "handempty", not: true},
         {cmd: "on", args: ["x", "y"], not: true}
      ]         
