problem:
  name: "BLOCKS-4-0"
  domain: "blocks"
  requirements:
    equality: False
    strips: False
    typing: True
  objects:
     - { name: "D", type: "block" }
     - { name: "B", type: "block" }
     - { name: "A", type: "block" }
     - { name: "C", type: "block" }
  init:
    - { name: "clear", args: ["C"] }
    - { name: "clear", args: ["A"] }
    - { name: "clear", args: ["B"] }
    - { name: "clear", args: ["D"] }
    - { name: "ontable", args: ["C"] }
    - { name: "ontable", args: ["A"] }
    - { name: "ontable", args: ["B"] }
    - { name: "ontable", args: ["D"] }
    - { name: "handempty" }
  goal:
    - { name: "on", args: ["D", "C"] }
    - { name: "on", args: ["C", "B"] }
    - { name: "on", args: ["B", "A"] }
